service: pinkman
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  timeout: 10
  region: ${param:region}
  memorySize: ${param:memorySize}
  apiGateway:
    apiKeys:
      - pinkman-${param:stageName}
  environment:
    STAGE_NAME: ${param:stageName}

# Stage parameters
params:
  # Values for the "prod" stage
  production:
    region: "us-east-1"
    memorySize: "128"
    stageName: "production"
  # Values for the "dev" stage
  development:
    region: "us-east-2"
    memorySize: "128" 
    stageName: "development"

package:
  patterns:
    - '!node_modules/**'
    - '*.yml'

functions:
  getEnvironmentList:
    handler: functions/api/getEnvironmentList.handler
    events:
      - http:
          path: environment-list
          method: get
          private: true